apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: billpay-ingress
  namespace: billpay
spec:
  ingressClassName: traefik  # <-- use 'nginx' if you have nginx ingress instead
  rules:
    - http:
        paths:
          # Frontend path
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          
